import { useLayoutEffect, useRef } from 'react'
import { Box } from '@mui/material'
import type { SxProps, Theme } from '@mui/material'
import { renderMath } from './renderMath.ts'
import { highlightCode } from './highlightCode.ts'
import { proseStyles } from './proseStyles.ts'

/**
 * Renders HTML that came from core's Markdown pipeline, typesets any maths in it (EZ-1732) and
 * highlights any code in it.
 *
 * Every place that shows `text_html`, `instructions_html`, `feedback_html`, a comment or a live
 * preview goes through here. That is the point: maths and code can appear in any of them — a
 * formula in an exercise, and a teacher answering with one in feedback — so a component per page
 * would be fourteen chances to forget one, and forgetting means a student sees `$x^2$`.
 *
 * It replaces the `<Box sx={…} dangerouslySetInnerHTML={{ __html }} />` these call sites used to
 * write inline, and takes the same `sx`.
 *
 * ## It also carries the styling
 *
 * [proseStyles] is applied here rather than by each caller, for the same reason the maths is: a
 * rule that every call site has to remember is a rule some call site will not have. That is not
 * hypothetical — the student exercise statement passed no `sx` at all, so until EZ-1729 it rendered
 * at user-agent defaults and a single long code line scrolled the whole statement sideways.
 *
 * A caller's `sx` is spread after it and still wins. What belongs in one now is local variation —
 * the smaller type of a comment bubble, a margin against a neighbour — not overflow safety or
 * typography.
 *
 * ## Why the innerHTML is set here and not by `dangerouslySetInnerHTML`
 *
 * Because typesetting has to happen *after* the HTML is in the DOM, and with React owning those
 * children there is no point at which that is safely true. The first version used
 * `dangerouslySetInnerHTML` and lost every formula: React re-set the container's children while
 * KaTeX's dynamic import was still in flight, so the typesetting landed on detached nodes. It
 * succeeded — no error, no warning — into a DOM that was no longer on the page.
 *
 * Assigning `innerHTML` in the effect takes those children out of React's hands entirely. React
 * renders an empty `<Box>`, never diffs inside it, and cannot replace what KaTeX has produced.
 * `renderMath` also re-queries after its import for the same reason; either fix alone would do, and
 * the failure was quiet enough to be worth both.
 *
 * **Still the same trust boundary, and still core's job.** Nothing here sanitises: the HTML is
 * generated by `MarkdownService` from Markdown, which escapes what it renders, and the maths arrives
 * as an attribute value that KaTeX parses as TeX rather than as markup. Setting `innerHTML` by hand
 * is exactly as dangerous as the prop whose name says so — no more, no less.
 *
 * `highlightCode` writes `innerHTML` a second time, and it stays inside that boundary: it reads
 * each block as `textContent`, so nothing an author wrote can re-enter the DOM as markup on that
 * path, and writes back only highlight.js's output, which escapes the source it was handed.
 */
export default function RenderedMarkdown({
  html,
  sx,
}: {
  html: string
  sx?: SxProps<Theme>
}) {
  const ref = useRef<HTMLDivElement>(null)

  // Layout effect, not a plain one: `dangerouslySetInnerHTML` used to put this content in during
  // the commit, so it was on screen at first paint. A `useEffect` would paint an empty box first
  // and then fill it — a visible flash and a layout jump on a page whose main content is this
  // element. Setting it in a layout effect restores the old timing.
  useLayoutEffect(() => {
    // Keyed on `html` rather than run once: the live preview in the exercise and feedback editors
    // replaces this content on every debounce tick, and each new formula needs typesetting.
    // `renderMath` skips what it has already done, so a re-render that changed nothing is cheap.
    const el = ref.current
    if (!el) return
    el.innerHTML = html
    // Independent of each other and both self-skipping on content they have already handled, so
    // they are started together rather than chained: neither needs the other's result, and a page
    // with maths but no code should not wait on the highlighter's import to typeset.
    void renderMath(el)
    void highlightCode(el)
  }, [html])

  return (
    <Box
      ref={ref}
      sx={[
        // The typography and overflow rules every caller inherits — see `proseStyles`. Listed
        // first so that a caller's own `sx`, spread after it, still wins.
        proseStyles,
        {
          // A displayed formula can be wider than the column it is in — a long alignment, a big
          // matrix — and KaTeX lays it out at its natural width. Without this the page itself
          // scrolls sideways, which is the one thing the layout must never do.
          '& .katex-display': { overflowX: 'auto', overflowY: 'hidden', py: 0.5 },
        },
        // MUI's documented way to let a caller's sx win over a component's own.
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
    />
  )
}
