import { useLayoutEffect, useRef } from 'react'
import { Box } from '@mui/material'
import type { SxProps, Theme } from '@mui/material'
import { renderMath } from './renderMath.ts'

/**
 * Renders HTML that came from core's Markdown pipeline, and typesets any maths in it (EZ-1732).
 *
 * Every place that shows `text_html`, `instructions_html`, `feedback_html`, a comment or a live
 * preview goes through here. That is the point: maths can appear in any of them — a formula in
 * an exercise, and a teacher answering with one in feedback — so a component per page would be
 * fourteen chances to forget one, and forgetting means a student sees `$x^2$`.
 *
 * It replaces the `<Box sx={…} dangerouslySetInnerHTML={{ __html }} />` these call sites used to
 * write inline, and takes the same `sx`.
 *
 * ## Why the innerHTML is set here and not by `dangerouslySetInnerHTML`
 *
 * Because typesetting has to happen *after* the HTML is in the DOM, and with React owning those
 * children there is no point at which that is safely true. The first version used
 * `dangerouslySetInnerHTML` and lost every formula: React re-set the container's children while
 * KaTeX's dynamic import was still in flight, so the typesetting landed on detached nodes. It
 * succeeded — no error, no warning — into a DOM that was no longer on the page.
 *
 * Assigning `innerHTML` in the effect takes those children out of React's hands entirely. React
 * renders an empty `<Box>`, never diffs inside it, and cannot replace what KaTeX has produced.
 * `renderMath` also re-queries after its import for the same reason; either fix alone would do, and
 * the failure was quiet enough to be worth both.
 *
 * **Still the same trust boundary, and still core's job.** Nothing here sanitises: the HTML is
 * generated by `MarkdownService` from Markdown, which escapes what it renders, and the maths arrives
 * as an attribute value that KaTeX parses as TeX rather than as markup. Setting `innerHTML` by hand
 * is exactly as dangerous as the prop whose name says so — no more, no less.
 */
export default function RenderedMarkdown({
  html,
  sx,
}: {
  html: string
  sx?: SxProps<Theme>
}) {
  const ref = useRef<HTMLDivElement>(null)

  // Layout effect, not a plain one: `dangerouslySetInnerHTML` used to put this content in during
  // the commit, so it was on screen at first paint. A `useEffect` would paint an empty box first
  // and then fill it — a visible flash and a layout jump on a page whose main content is this
  // element. Setting it in a layout effect restores the old timing.
  useLayoutEffect(() => {
    // Keyed on `html` rather than run once: the live preview in the exercise and feedback editors
    // replaces this content on every debounce tick, and each new formula needs typesetting.
    // `renderMath` skips what it has already done, so a re-render that changed nothing is cheap.
    const el = ref.current
    if (!el) return
    el.innerHTML = html
    void renderMath(el)
  }, [html])

  return (
    <Box
      ref={ref}
      sx={[
        {
          // A displayed formula can be wider than the column it is in — a long alignment, a big
          // matrix — and KaTeX lays it out at its natural width. Without this the page itself
          // scrolls sideways, which is the one thing the layout must never do.
          '& .katex-display': { overflowX: 'auto', overflowY: 'hidden', py: 0.5 },
        },
        // MUI's documented way to let a caller's sx win over a component's own.
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
    />
  )
}
