import config from '../config.ts'
import { record } from '../features/bug-report/breadcrumbs.ts'

export interface ApiError {
  id: string
  code: string | null
  attrs: Record<string, string>
  log_msg: string
}

export class ApiResponseError extends Error {
  // Declared and assigned explicitly rather than as constructor parameter properties:
  // those are TS-only syntax, which `erasableSyntaxOnly` forbids.
  readonly status: number
  readonly errorBody: ApiError | null

  constructor(status: number, errorBody: ApiError | null) {
    super(errorBody?.log_msg ?? `HTTP ${status}`)
    this.status = status
    this.errorBody = errorBody
  }
}

export let getToken: (() => Promise<string | undefined>) | null = null

export function setTokenProvider(provider: () => Promise<string | undefined>) {
  getToken = provider
}

export async function apiFetch<T>(
  path: string,
  options: {
    method?: string
    body?: unknown
    headers?: Record<string, string>
    noAuth?: boolean
  } = {},
): Promise<T> {
  const { method = 'GET', body, headers = {}, noAuth = false } = options

  const isFormData = body instanceof FormData

  const combinedHeaders: Record<string, string> = {
    'Content-Type': 'application/json',
    ...headers,
  }

  // Deleted, not overridden. A multipart body needs `multipart/form-data; boundary=…`, and the
  // boundary is generated by the browser when it serialises the FormData — there is no way to know
  // it here. Setting the header by hand omits it, and the request then fails server-side looking
  // like a corrupt upload rather than a client bug.
  if (isFormData) delete combinedHeaders['Content-Type']

  if (!noAuth && getToken) {
    const token = await getToken()
    if (token) {
      combinedHeaders['Authorization'] = `Bearer ${token}`
    }
  }

  const response = await fetch(`${config.emsRoot}${path}`, {
    method,
    headers: combinedHeaders,
    body: isFormData ? body : body != null ? JSON.stringify(body) : undefined,
  })

  if (!response.ok) {
    let errorBody: ApiError | null = null
    try {
      errorBody = await response.json()
    } catch {
      // no parseable error body
    }

    // The one place every core call fails, so the one place worth recording them (EZ-1786).
    //
    // `errorBody.id` is the reason this is here rather than just logging a status. Core mints that
    // UUID in its exception handler and writes the *same* value to its log line, to this response
    // and to the admin email — so a bug report carrying these ids gives whoever picks it up an exact
    // grep key into the backend log, instead of a timestamp and a username to search around.
    record('api', `${method} ${path} -> ${response.status}${errorBody?.id ? ` id=${errorBody.id}` : ''}`)

    throw new ApiResponseError(response.status, errorBody)
  }

  if (response.status === 204) {
    return undefined as T
  }

  const text = await response.text()
  if (!text) {
    return undefined as T
  }
  return JSON.parse(text)
}