package core.ems.service.exercise

import com.fasterxml.jackson.annotation.JsonProperty
import core.conf.security.EasyUser
import core.db.ExerciseVer
import core.ems.service.MarkdownService
import io.github.oshai.kotlinlogging.KotlinLogging
import jakarta.validation.Valid
import org.jetbrains.exposed.v1.core.and
import org.jetbrains.exposed.v1.core.eq
import org.jetbrains.exposed.v1.core.isNull
import org.jetbrains.exposed.v1.jdbc.select
import org.jetbrains.exposed.v1.jdbc.transactions.transaction
import org.jetbrains.exposed.v1.jdbc.update
import org.springframework.security.access.annotation.Secured
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

/**
 * Re-render `exercise_version.text_html` from `text_md`, in place.
 *
 * ### Why this needs to exist at all
 *
 * `text_html` is derived from `text_md` by [MarkdownService] **once, at save time**. So a change to
 * the renderer reaches nothing that already exists: every exercise keeps the HTML produced by
 * whichever renderer was running the day a teacher last pressed save. Same shape as
 * [AdminRecompileTslController], and this is its sibling — read that docblock too, the reasoning
 * about version chains is the same reasoning.
 *
 * EZ-1732 is the demonstration. It taught the renderer to typeset maths, and reached none of the 48
 * exercises that contain formulae: their `text_md` has `$…$` in it and their stored HTML was rendered
 * before maths existed, so they still show raw dollars on a build that supports them.
 *
 * ### Why every exercise and not only the ones with maths
 *
 * Because the maths is the smaller half. **Drift between stored HTML and what the renderer produces
 * today is a trap for the next teacher who edits that exercise**: they fix a typo, save, and the text
 * changes underneath them — not from their edit, but because the HTML was regenerated by a newer
 * renderer than the one that produced what they were looking at. Converging everything now makes that
 * one admin action with a report somebody read, instead of a surprise handed to whoever edits next.
 *
 * The dry run is how that stays honest: if the changed count is far above the ~48 maths exercises,
 * something else has drifted and is worth understanding before it is written.
 *
 * ### Why in place, and not through the rewrite endpoint
 *
 * `PUT /v2/admin/exercises/{id}/rewrite` already exists for mechanical migrations and is careful
 * about attribution — it carries `author` and `valid_from` forward so a migration does not look like
 * an edit. But it still inserts a **new version row**, which is right when the *source* changes
 * (the adoc→Markdown conversion rewrote `text_md`, so there was a new authored state to record) and
 * wrong here.
 *
 * Nothing authored changes. `text_md` is untouched, and `text_html` is derived data — the same
 * category as TSL's `generated_*.py`. Recording a thousand new versions to say that a renderer
 * improved would make the version chain a worse record of what teachers actually did, and would
 * double the table to store no new information.
 *
 * ### Current versions only
 *
 * `valid_to IS NULL`. An older version's `text_html` is a record of what that version rendered, and
 * rewriting it would be editing history to say something that was never true. It is also the only
 * version anyone can see.
 *
 * ### Dry run by default
 *
 * `apply` defaults to false and the response is identical either way, so the report is a rehearsal
 * of the write rather than a different code path describing one. Byte-identical output is reported
 * `UNCHANGED` and **writes nothing**, which is what makes the changed count mean something.
 */
@RestController
@RequestMapping("/v2")
class AdminRerenderMarkdownController(private val markdownService: MarkdownService) {
    private val log = KotlinLogging.logger {}

    data class Req(
        /** False rehearses and writes nothing. The default is deliberate; see the class docblock. */
        @param:JsonProperty("apply") val apply: Boolean = false,
        /** Optional filter. Absent means every current exercise. */
        @param:JsonProperty("exercise_ids") val exerciseIds: List<Long>? = null,
    )

    data class Resp(
        @get:JsonProperty("applied") val applied: Boolean,
        @get:JsonProperty("scanned") val scanned: Int,
        @get:JsonProperty("changed") val changed: Int,
        @get:JsonProperty("unchanged") val unchanged: Int,
        @get:JsonProperty("failed") val failed: Int,
        /** Present so the four outcome counts sum to [scanned]. */
        @get:JsonProperty("skipped") val skipped: Int,
        /**
         * Ids given in `exercise_ids` that are not a current exercise.
         *
         * Without it, asking about a retired id returns `scanned: 0`, which is indistinguishable
         * from "looked, nothing to do" — and this endpoint's whole safety story is reading the dry
         * run first.
         */
        @get:JsonProperty("not_found") val notFound: List<Long>,
        @get:JsonProperty("results") val results: List<ExerciseResp>,
    )

    data class ExerciseResp(
        @get:JsonProperty("exercise_id") val exerciseId: Long,
        @get:JsonProperty("outcome") val outcome: Outcome,
        /** Stored and freshly rendered lengths, so a report can be skimmed for surprises. */
        @get:JsonProperty("stored_length") val storedLength: Int?,
        @get:JsonProperty("rendered_length") val renderedLength: Int?,
        /** Why, for FAILED and SKIPPED. */
        @get:JsonProperty("detail") val detail: String?,
    )

    enum class Outcome {
        /** The freshly rendered HTML differs from the stored HTML. Rewritten if `apply` was true. */
        CHANGED,

        /** Byte-identical. Nothing written. */
        UNCHANGED,

        /** Rendering threw. **The stored HTML is left exactly as it was.** */
        FAILED,

        /** No `text_md` — authored in AsciiDoc and never converted, so there is nothing to render. */
        SKIPPED,
    }

    @Secured("ROLE_ADMIN")
    @PostMapping("/admin/exercises/markdown/rerender")
    fun controller(@Valid @RequestBody req: Req, caller: EasyUser): Resp {
        log.info {
            "${caller.id} is re-rendering exercise Markdown (apply=${req.apply}, " +
                    "ids=${req.exerciseIds?.size?.let { "$it given" } ?: "all"})"
        }

        val targets = selectCurrentExercises(req.exerciseIds)
        // One transaction per exercise rather than one for the run, exactly as the TSL recompile
        // does: a run over a thousand exercises must not be all-or-nothing, and an interrupted run
        // should leave what it finished in a good state.
        val results = targets.map { rerenderOne(it, req.apply) }

        val resp = Resp(
            applied = req.apply,
            scanned = results.size,
            changed = results.count { it.outcome == Outcome.CHANGED },
            unchanged = results.count { it.outcome == Outcome.UNCHANGED },
            failed = results.count { it.outcome == Outcome.FAILED },
            skipped = results.count { it.outcome == Outcome.SKIPPED },
            notFound = req.exerciseIds.orEmpty().filterNot { id -> targets.any { it.exerciseId == id } }.sorted(),
            results = results,
        )
        log.info {
            "Markdown re-render ${if (req.apply) "applied" else "(DRY RUN)"}: ${resp.scanned} scanned, " +
                    "${resp.changed} changed, ${resp.unchanged} unchanged, ${resp.failed} failed, " +
                    "${resp.skipped} skipped" +
                    if (resp.notFound.isEmpty()) "" else ", ${resp.notFound.size} id(s) not a current exercise"
        }
        return resp
    }

    /** [versionId] is what the staleness guard compares against; see [rerenderWithin]. */
    internal data class Target(val exerciseId: Long, val versionId: Long)

    private fun selectCurrentExercises(only: List<Long>?): List<Target> = transaction {
        ExerciseVer
            .select(ExerciseVer.id, ExerciseVer.exercise)
            .where { ExerciseVer.validTo.isNull() }
            .map { Target(it[ExerciseVer.exercise].value, it[ExerciseVer.id].value) }
            .let { all -> if (only == null) all else all.filter { it.exerciseId in only } }
            .sortedBy { it.exerciseId }
    }

    /**
     * One exercise, in its own transaction, and **nothing it can throw ends the run**.
     *
     * `Throwable` rather than `Exception`, for the reason `AdminRecompileTsl` gives: every exercise
     * commits separately, so an escape would leave the admin with a 500 and no record of the
     * hundreds already rewritten. A run that cannot say what it did is worse than one that did less.
     */
    private fun rerenderOne(target: Target, apply: Boolean): ExerciseResp = try {
        transaction { rerenderWithin(target, apply) }
    } catch (e: Throwable) {
        log.warn(e) { "Markdown re-render threw for exercise ${target.exerciseId}" }
        ExerciseResp(target.exerciseId, Outcome.FAILED, null, null, describe(e))
    }

    /**
     * `internal` so a test can hand it a [Target] that is deliberately superseded.
     *
     * The staleness it guards against needs a *concurrent* save during a long run, and driving the
     * endpoint cannot produce that interleaving — one request scans and writes with nothing in
     * between. Calling this directly with an already-superseded version is the only way to execute
     * the guard, and a guard whose branch no test has run is a guard nobody has checked.
     */
    internal fun rerenderWithin(target: Target, apply: Boolean): ExerciseResp {
        // Re-read this version inside the transaction and stop if it is no longer current.
        //
        // A teacher saving mid-run closes this row and opens a new one. Writing here would then be
        // rewriting a superseded version — the history edit this endpoint promises not to do — while
        // the version that people actually see keeps its stale HTML and the report claims success.
        val row = ExerciseVer
            .select(ExerciseVer.textMd, ExerciseVer.textHtml, ExerciseVer.validTo)
            .where { (ExerciseVer.id eq target.versionId) and ExerciseVer.validTo.isNull() }
            .singleOrNull()

        if (row == null) {
            return ExerciseResp(
                target.exerciseId, Outcome.SKIPPED, null, null,
                "the exercise was saved while this run was in progress; re-render again",
            )
        }

        val md = row[ExerciseVer.textMd]
        val storedHtml = row[ExerciseVer.textHtml]

        // Nothing to render from. These are the exercises still authored in AsciiDoc, whose
        // `text_html` is the only rendering that exists — emphatically not to be blanked.
        if (md == null) {
            return ExerciseResp(
                target.exerciseId, Outcome.SKIPPED, storedHtml?.length, null,
                "no text_md; authored in AsciiDoc and not converted",
            )
        }

        val rendered = markdownService.mdToHtml(md)

        if (rendered == storedHtml) {
            return ExerciseResp(
                target.exerciseId, Outcome.UNCHANGED, storedHtml?.length, rendered.length, null,
            )
        }

        if (apply) {
            // `text_html` only. `text_md` is the source and is never touched, and neither is
            // `author`, `valid_from` or `valid_to` — the row keeps saying who authored it and when.
            ExerciseVer.update({ ExerciseVer.id eq target.versionId }) {
                it[textHtml] = rendered
            }
            log.info {
                "Re-rendered exercise ${target.exerciseId} " +
                        "(${storedHtml?.length ?: 0} -> ${rendered.length} chars)"
            }
        }

        return ExerciseResp(
            target.exerciseId, Outcome.CHANGED, storedHtml?.length, rendered.length, null,
        )
    }

    /** The first line of why something failed, short enough to sit in a list of a thousand. */
    private fun describe(e: Throwable): String =
        (e.message ?: e::class.simpleName).orEmpty().lines().first().take(300)
}
