enum class PageName {
    COURSES,
    EXERCISES,
    EXERCISE_SUMMARY,
    PARTICIPANTS,
    GRADE_TABLE,
    EXERCISE_LIBRARY,
    EXERCISE,
    EMBED_ANON_AUTOASSESS,
    LINK_REGISTER,
    LINK_JOIN_COURSE,
}
