enum class PageName {
    COURSES,
    EXERCISES,
    EXERCISE_SUMMARY,
    ADD_COURSE,
    PARTICIPANTS,
    GRADE_TABLE,
    NEW_EXERCISE,
    EXERCISE_LIBRARY,
    EXERCISE,
    EMBED_ANON_AUTOASSESS,
    LINK_REGISTER,
}
