/**
 * The assessment tab on a teacher's course exercise, which shows the auto-assessment config.
 *
 * It used to be a placeholder reading "auto-assessment configuration will appear here", next to
 * two chips repeating the header. The server had been sending the whole configuration all along —
 * script, container, limits, assets — and `TeacherExerciseDetails` simply did not declare any of
 * it, so there was nothing typed to render. A gap that shape is invisible to a type checker and to
 * every test that does not open the tab, which is why this script exists.
 *
 * The limits in the fixture are deliberately **not** the values the container's template carries
 * (Python Grader defaults to 7s/30MB). If the tab ever renders a template default instead of what
 * the response said, these assertions fail rather than passing on a plausible-looking number.
 */
import { test } from '../support/spec.mjs'
import { fakeApi, waitUntil, BASE_URL } from '../support/harness.mjs'

const COURSE = '119'
const CE = '4147'
const EX = '9001'

const tslSpec = {
  language: 'python3',
  validateFiles: true,
  requiredFiles: ['lahendus.py'],
  tslVersion: '1.0',
  tests: [
    {
      type: 'program_execution_test',
      id: 1001,
      name: 'Adds two numbers',
      standardInputData: ['2', '3'],
      inputFiles: [],
      genericChecks: [],
      outputFileChecks: [],
      exceptionCheck: null,
    },
  ],
}

/** A script-graded exercise, with limits and an asset that no template would supply. */
const scriptGraded = {
  exercise_id: EX,
  title: 'Sum of two numbers',
  title_alias: null,
  text_html: '<p>Read two integers and print their sum.</p>',
  text_md: 'Read two integers and print their sum.',
  instructions_html: null,
  instructions_md: null,
  soft_deadline: null,
  hard_deadline: null,
  grader_type: 'AUTO',
  solution_file_name: 'lahendus.py',
  solution_file_type: 'TEXT_EDITOR',
  threshold: 100,
  last_modified: '2026-07-30T12:00:00.000Z',
  student_visible: true,
  student_visible_from: null,
  assessments_student_visible: true,
  grading_script: 'python grade.py --strict',
  container_image: 'pygrader',
  max_time_sec: 12,
  max_mem_mb: 44,
  assets: [{ file_name: 'helper.py', file_content: 'EXPECTED = 5\n' }],
  executors: [{ id: '1', name: 'mock-executor' }],
  has_lib_access: true,
  exception_students: null,
  exception_groups: null,
}

const tslGraded = {
  ...scriptGraded,
  grading_script: 'cd student-submission\npython generated_0.py',
  container_image: 'tiivad:tsl-compose',
  assets: [
    { file_name: 'tsl.json', file_content: JSON.stringify(tslSpec, null, 4) },
    { file_name: 'generated_0.py', file_content: '# regenerated by the server on save' },
  ],
}

const teacherGraded = {
  ...scriptGraded,
  grader_type: 'TEACHER',
  grading_script: null,
  container_image: null,
  max_time_sec: null,
  max_mem_mb: null,
  assets: null,
  executors: null,
}

let courseExercise = scriptGraded

test('course-exercise-assessment', async ({ launch, check }) => {
  const { page, shot, close } = await launch({ role: 'teacher,admin', shotPrefix: 'ce-assess-' })

  await fakeApi(page, [
    ['/account/checkin', () => ({})],
    ['/participants', () => ({ students: [], teachers: [], students_pending: [], students_moodle_pending: [] })],
    ['/groups', () => ({ groups: [] })],
    // `latest_submissions`, because the hook maps that field off the response — returning the wrong
    // shape here yields undefined and a react-query console error, which is where a real one hides.
    [`/teacher/courses/${COURSE}/exercises/${CE}/submissions/latest/students`, () => ({ latest_submissions: [] })],
    // `/submissions/latest/students` first, because it is the one endpoint under `/submissions/`
    // that answers with something else entirely: core sends the whole ExercisesResp, and the hook
    // reads `.latest_submissions` off it. Falling through to the family stub below yields
    // `undefined` and react-query logs "Query data cannot be undefined" on every run.
    //
    // Anchoring the course-exercise handler silenced fakeApi's [broad stub] warning without fixing
    // what the warning pointed at — the request simply moved one handler down. Caught in review.
    [/\/submissions\/latest\/students(\?|$)/, () => ({ latest_submissions: [] })],
    ['/submissions/', () => ({ submissions: [], count: 0 })],
    ['/latest', () => ({ submissions: [], count: 0 })],
    [`/student/courses/${COURSE}/exercises`, () => ({ exercises: [] })],
    // Must precede the bare `/teacher/courses`, which matches this URL as a substring.
    [`/teacher/courses/${COURSE}/exercises/${CE}`, () => courseExercise],
    ['/teacher/courses', () => ({ courses: [] })],
  ], { log: false })

  async function openAssessmentTab() {
    await page.goto(`${BASE_URL}/courses/${COURSE}/exercises/${CE}`)
    await page.getByText('Sum of two numbers').first().waitFor()
    await page.getByRole('tab', { name: 'Assessment' }).click()
  }

  // --- a script-graded exercise -------------------------------------------------------------------

  await openAssessmentTab()

  check(
    'the placeholder is gone',
    !(await page.getByText('configuration will appear here').isVisible().catch(() => false)),
  )
  check(
    'it says where the config actually lives',
    await waitUntil(() => page.getByText(/Configured in the exercise library/).isVisible()),
  )

  // The five settings are one dense line here rather than five labelled inputs: they are read-only
  // on this page and were most of what the tab showed. Every value still has to be on screen.
  // Located as the one paragraph carrying the eval type, so the assertions below are about a single
  // line rather than five values scattered anywhere on the page. No data-testid: nothing else in
  // this app has one, and role/text is how the rest of these scripts locate things.
  const summary = () => page.locator('p').filter({ hasText: 'lahendus.py' }).first().innerText()
  check('the settings collapse to one line', await waitUntil(async () => (await summary()).includes('·')))
  for (const [what, value] of [
    ['the solution file name', 'lahendus.py'],
    ['the submission type', 'Text editor'],
    ['the auto-assessment type', 'Python Grader'],
    // Not the container template's defaults (7s/30MB) — these come from the response or not at all.
    ['max time, from the response rather than the template', '12 s'],
    ['max memory too', '44 MB'],
  ]) {
    check(`the summary carries ${what}`, (await summary()).includes(value))
  }

  // Read-only: the config belongs to the library exercise, so editing it here would change grading
  // for every other course using it. The inputs are absent rather than disabled.
  for (const name of ['Solution file name', 'Max time (s)', 'Max memory (MB)']) {
    check(`there is no editable "${name}" field`, (await page.getByRole('textbox', { name }).count()) === 0)
  }
  check(
    'nor a type selector',
    (await page.getByRole('combobox', { name: 'Test framework' }).count()) === 0,
  )

  // The labels have to survive somewhere, or the line is five unexplained values.
  await page.getByText('lahendus.py', { exact: true }).hover()
  check(
    'hovering a value names the field it came from',
    await waitUntil(() => page.getByRole('tooltip').filter({ hasText: 'Solution file name' }).isVisible()),
  )

  check(
    'the grading script is still rendered',
    await waitUntil(async () => (await page.locator('.cm-content').first().innerText()).includes('grade.py')),
  )
  check('and the asset still has its own file tab', await page.getByRole('tab', { name: 'helper.py' }).isVisible())

  await shot('script-graded')

  // --- a TSL exercise, which renders through the visual builder ------------------------------------

  courseExercise = tslGraded
  await openAssessmentTab()

  check('a TSL exercise shows as TSL', await waitUntil(async () => (await summary()).includes('TSL')))
  check(
    'and its spec renders in the builder rather than as raw JSON',
    await waitUntil(() => page.getByText('Adds two numbers').first().isVisible()),
  )

  await shot('tsl')

  // --- a teacher-graded exercise -------------------------------------------------------------------

  courseExercise = teacherGraded
  await openAssessmentTab()

  check(
    'a teacher-graded exercise says so instead of showing an empty config',
    await waitUntil(() => page.getByText(/no tests/).isVisible()),
  )

  await shot('teacher-graded')

  await close()
})
